
name: Generate Tokens On Input

on:
  push:
    paths:
      - 'input/design-tokens.json'

jobs:
  generate_tokens:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with: 
       node-version: '16'
     - name: Install Node Dependencies
     - run: npm install
     - name: token-transformer
     - run: token-transformer tokens.json output.json
     - name: Build Style Dictionary
     - run: npm run build
     - name: Commit Generated Platform Deliverables
       id: "auto-commit-action"
     - uses: stefanzweifel/git-auto-commit-action@v4
       with:
        commit_message: Update platform deliverables
        branch: token-transformer-
